2019-10-09 16:04:09,484 INFO Connecting to TGC socket...
2019-10-09 16:04:10,490 INFO Connected.
2019-10-09 16:04:10,490 INFO Recording brain data...
2019-10-09 16:14:19,253 INFO Connecting to TGC socket...
2019-10-09 16:14:20,261 INFO Connected.
2019-10-09 16:14:20,262 INFO Recording brain data...
2019-10-09 16:20:18,963 INFO Connecting to TGC socket...
2019-10-09 16:20:19,970 INFO Connected.
2019-10-09 16:20:19,971 INFO Recording brain data...
2019-10-09 16:23:36,732 INFO Connecting to TGC socket...
2019-10-09 16:23:37,740 INFO Connected.
2019-10-09 16:23:37,740 INFO Recording brain data...
2019-10-09 16:24:13,564 INFO Connecting to TGC socket...
2019-10-09 16:24:14,572 INFO Connected.
2019-10-09 16:24:14,573 INFO Recording brain data...
2019-10-09 16:24:41,642 INFO Connecting to TGC socket...
2019-10-09 16:24:42,649 INFO Connected.
2019-10-09 16:24:42,649 INFO Recording brain data...
2019-10-09 16:26:21,836 INFO Connecting to TGC socket...
2019-10-09 16:26:22,844 INFO Connected.
2019-10-09 16:26:22,844 INFO Recording brain data...
2019-10-09 16:26:23,391 ERROR Exception:
Traceback (most recent call last):
  File "D:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 120, in <module>
    conn.record_data()
  File "D:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 82, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-09 16:26:23,392 ERROR No connection with TGC socket
2019-10-09 16:27:15,935 INFO Connecting to TGC socket...
2019-10-09 16:27:16,941 INFO Connected.
2019-10-09 16:27:16,941 INFO Recording brain data...
2019-10-09 16:27:47,461 INFO Connecting to TGC socket...
2019-10-09 16:27:48,469 INFO Connected.
2019-10-09 16:27:48,469 INFO Recording brain data...
2019-10-09 16:31:46,148 INFO Connecting to TGC socket...
2019-10-09 16:31:47,156 INFO Connected.
2019-10-09 16:31:47,156 INFO Recording brain data...
2019-10-09 16:34:36,393 INFO Connecting to TGC socket...
2019-10-09 16:34:37,401 INFO Connected.
2019-10-09 16:34:37,401 INFO Recording brain data...
2019-10-09 16:35:55,780 INFO Connecting to TGC socket...
2019-10-09 16:35:56,786 INFO Connected.
2019-10-09 16:35:56,786 INFO Recording brain data...
2019-10-09 16:39:51,790 INFO Connecting to TGC socket...
2019-10-09 16:39:52,797 INFO Connected.
2019-10-09 16:39:52,797 INFO Recording brain data...
2019-10-09 16:40:53,410 INFO Connecting to TGC socket...
2019-10-09 16:40:54,416 INFO Connected.
2019-10-09 16:40:54,416 INFO Recording brain data...
2019-10-09 16:48:55,952 INFO Connecting to TGC socket...
2019-10-09 16:48:56,960 INFO Connected.
2019-10-09 16:48:56,960 INFO Recording brain data...
2019-10-09 16:55:05,923 INFO Connecting to TGC socket...
2019-10-09 16:55:06,935 INFO Connected.
2019-10-09 16:55:06,935 INFO Recording brain data...
2019-10-09 16:58:29,491 INFO Connecting to TGC socket...
2019-10-09 16:58:30,505 INFO Connected.
2019-10-09 16:58:30,505 INFO Recording brain data...
2019-10-09 16:59:10,340 INFO Connecting to TGC socket...
2019-10-09 16:59:11,353 INFO Connected.
2019-10-09 16:59:11,354 INFO Recording brain data...
2019-10-09 16:59:12,104 ERROR Exception:
Traceback (most recent call last):
  File "D:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 121, in <module>
    conn.record_data()
  File "D:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 82, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-09 16:59:12,104 ERROR No connection with TGC socket
2019-10-09 17:00:12,095 INFO Connecting to TGC socket...
2019-10-09 17:00:13,106 INFO Connected.
2019-10-09 17:00:13,107 INFO Recording brain data...
2019-10-09 20:56:26,989 INFO Connecting to TGC socket...
2019-10-09 20:56:29,292 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:56:29,375 ERROR No connection with TGC socket
2019-10-09 20:58:28,082 INFO Connecting to TGC socket...
2019-10-09 20:58:30,092 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:58:30,096 ERROR No connection with TGC socket
2019-10-09 20:58:59,909 INFO Connecting to TGC socket...
2019-10-09 20:59:01,917 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:59:01,921 ERROR No connection with TGC socket
2019-10-09 20:59:08,244 INFO Connecting to TGC socket...
2019-10-09 20:59:10,255 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:59:10,259 ERROR No connection with TGC socket
2019-10-09 20:59:50,492 INFO Connecting to TGC socket...
2019-10-09 20:59:52,507 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:59:52,509 ERROR No connection with TGC socket
2019-10-09 20:59:52,924 INFO Connecting to TGC socket...
2019-10-09 20:59:54,932 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:59:54,934 ERROR No connection with TGC socket
2019-10-09 21:00:18,824 INFO Connecting to TGC socket...
2019-10-09 21:00:20,833 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 21:00:20,834 ERROR No connection with TGC socket
2019-10-09 21:00:40,501 INFO Connecting to TGC socket...
2019-10-09 21:00:42,510 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 21:00:42,514 ERROR No connection with TGC socket
2019-10-09 21:00:50,200 INFO Connecting to TGC socket...
2019-10-09 21:00:52,211 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 21:00:52,215 ERROR No connection with TGC socket
2019-10-09 21:17:21,107 INFO Connecting to TGC socket...
2019-10-09 21:17:22,115 INFO Connected.
2019-10-09 21:17:22,148 INFO Recording brain data...
2019-10-09 21:30:05,139 INFO Connecting to TGC socket...
2019-10-09 21:30:06,148 INFO Connected.
2019-10-09 21:30:06,148 INFO Recording brain data...
2019-10-09 22:01:41,772 INFO Connecting to TGC socket...
2019-10-09 22:01:42,794 INFO Connected.
2019-10-09 22:01:42,795 INFO Recording brain data...
2019-10-09 22:04:37,490 INFO Connecting to TGC socket...
2019-10-09 22:04:38,511 INFO Connected.
2019-10-09 22:04:38,512 INFO Recording brain data...
2019-10-09 22:26:32,673 INFO Connecting to TGC socket...
2019-10-09 22:26:33,702 INFO Connected.
2019-10-09 22:26:33,702 INFO Recording brain data...
2019-10-09 22:27:44,325 INFO Connecting to TGC socket...
2019-10-09 22:27:45,343 INFO Connected.
2019-10-09 22:27:45,345 INFO Recording brain data...
2019-10-09 22:28:07,566 INFO Connecting to TGC socket...
2019-10-09 22:28:08,586 INFO Connected.
2019-10-09 22:28:08,586 INFO Recording brain data...
2019-10-09 22:37:02,450 INFO Connecting to TGC socket...
2019-10-09 22:37:03,472 INFO Connected.
2019-10-09 22:37:03,473 INFO Recording brain data...
2019-10-09 22:37:54,495 INFO Connecting to TGC socket...
2019-10-09 22:37:55,512 INFO Connected.
2019-10-09 22:37:55,513 INFO Recording brain data...
2019-10-09 22:38:39,878 INFO Connecting to TGC socket...
2019-10-09 22:38:40,894 INFO Connected.
2019-10-09 22:38:40,895 INFO Recording brain data...
2019-10-09 22:39:03,913 INFO Connecting to TGC socket...
2019-10-09 22:39:04,933 INFO Connected.
2019-10-09 22:39:04,934 INFO Recording brain data...
2019-10-09 22:39:57,142 INFO Connecting to TGC socket...
2019-10-09 22:39:58,157 INFO Connected.
2019-10-09 22:39:58,157 INFO Recording brain data...
2019-10-09 22:40:24,048 INFO Connecting to TGC socket...
2019-10-09 22:40:25,070 INFO Connected.
2019-10-09 22:40:25,070 INFO Recording brain data...
2019-10-09 23:05:17,526 INFO Connecting to TGC socket...
2019-10-09 23:05:18,542 INFO Connected.
2019-10-09 23:05:18,543 INFO Recording brain data...
2019-10-09 23:05:50,706 INFO Connecting to TGC socket...
2019-10-09 23:05:51,724 INFO Connected.
2019-10-09 23:05:51,725 INFO Recording brain data...
2019-10-09 23:08:23,650 INFO Connecting to TGC socket...
2019-10-09 23:08:24,668 INFO Connected.
2019-10-09 23:08:24,668 INFO Recording brain data...
2019-10-09 23:09:30,696 INFO Connecting to TGC socket...
2019-10-09 23:09:32,728 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 122, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 23:09:32,729 ERROR No connection with TGC socket
2019-10-09 23:10:34,267 INFO Connecting to TGC socket...
2019-10-09 23:10:36,289 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 122, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 23:10:36,290 ERROR No connection with TGC socket
2019-10-09 23:12:26,874 INFO Connecting to TGC socket...
2019-10-09 23:12:28,894 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 122, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 23:12:28,898 ERROR No connection with TGC socket
2019-10-09 23:16:08,630 INFO Connecting to TGC socket...
2019-10-09 23:16:09,647 INFO Connected.
2019-10-09 23:16:09,649 INFO Recording brain data...
2019-10-09 23:16:10,206 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 125, in <module>
    conn.record_data()
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 84, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-09 23:16:10,206 ERROR No connection with TGC socket
2019-10-09 23:17:29,359 INFO Connecting to TGC socket...
2019-10-09 23:17:30,375 INFO Connected.
2019-10-09 23:17:30,376 INFO Recording brain data...
2019-10-09 23:18:16,513 INFO Connecting to TGC socket...
2019-10-09 23:18:17,529 INFO Connected.
2019-10-09 23:18:17,530 INFO Recording brain data...
2019-10-09 23:19:54,865 INFO Connecting to TGC socket...
2019-10-09 23:19:55,901 INFO Connected.
2019-10-09 23:19:55,901 INFO Recording brain data...
2019-10-09 23:23:58,164 INFO Connecting to TGC socket...
2019-10-09 23:23:59,180 INFO Connected.
2019-10-09 23:23:59,181 INFO Recording brain data...
2019-10-09 23:24:40,271 INFO Connecting to TGC socket...
2019-10-09 23:24:41,292 INFO Connected.
2019-10-09 23:24:41,292 INFO Recording brain data...
2019-10-09 23:26:21,916 INFO Connecting to TGC socket...
2019-10-09 23:26:22,937 INFO Connected.
2019-10-09 23:26:22,939 INFO Recording brain data...
2019-10-09 23:27:04,859 INFO Connecting to TGC socket...
2019-10-09 23:27:05,878 INFO Connected.
2019-10-09 23:27:05,879 INFO Recording brain data...
2019-10-09 23:27:38,190 INFO Connecting to TGC socket...
2019-10-09 23:27:39,211 INFO Connected.
2019-10-09 23:27:39,212 INFO Recording brain data...
2019-10-09 23:30:40,647 INFO Connecting to TGC socket...
2019-10-09 23:30:41,666 INFO Connected.
2019-10-09 23:30:41,666 INFO Recording brain data...
2019-10-09 23:32:20,645 INFO Connecting to TGC socket...
2019-10-09 23:32:21,676 INFO Connected.
2019-10-09 23:32:21,677 INFO Recording brain data...
2019-10-09 23:34:44,128 INFO Connecting to TGC socket...
2019-10-09 23:34:45,148 INFO Connected.
2019-10-09 23:34:45,149 INFO Recording brain data...
2019-10-09 23:37:01,137 INFO Connecting to TGC socket...
2019-10-09 23:37:02,156 INFO Connected.
2019-10-09 23:37:02,157 INFO Recording brain data...
2019-10-10 00:03:17,969 INFO Connecting to TGC socket...
2019-10-10 00:03:18,985 INFO Connected.
2019-10-10 00:03:18,985 INFO Recording brain data...
2019-10-10 00:04:45,976 INFO Connecting to TGC socket...
2019-10-10 00:04:46,995 INFO Connected.
2019-10-10 00:04:46,996 INFO Recording brain data...
2019-10-10 00:09:46,366 INFO Connecting to TGC socket...
2019-10-10 00:09:47,385 INFO Connected.
2019-10-10 00:09:47,385 INFO Recording brain data...
2019-10-10 00:23:21,067 INFO Connecting to TGC socket...
2019-10-10 00:23:22,085 INFO Connected.
2019-10-10 00:23:22,086 INFO Recording brain data...
2019-10-10 00:23:22,728 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 125, in <module>
    conn.record_data()
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 84, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-10 00:23:22,728 ERROR No connection with TGC socket
2019-10-10 00:24:19,919 INFO Connecting to TGC socket...
2019-10-10 00:24:20,938 INFO Connected.
2019-10-10 00:24:20,938 INFO Recording brain data...
2019-10-10 00:25:14,243 INFO Connecting to TGC socket...
2019-10-10 00:25:15,260 INFO Connected.
2019-10-10 00:25:15,261 INFO Recording brain data...
2019-10-10 00:26:47,816 INFO Connecting to TGC socket...
2019-10-10 00:26:48,831 INFO Connected.
2019-10-10 00:26:48,832 INFO Recording brain data...
2019-10-10 00:31:40,149 INFO Connecting to TGC socket...
2019-10-10 00:31:41,169 INFO Connected.
2019-10-10 00:31:41,169 INFO Recording brain data...
2019-10-30 09:30:21,090 INFO Connecting to TGC socket...
2019-10-30 09:30:22,314 INFO Connected.
2019-10-30 09:30:22,314 INFO Recording brain data...
2019-10-30 09:30:23,305 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 125, in <module>
    conn.record_data()
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 84, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-30 09:30:23,318 ERROR No connection with TGC socket
2019-10-30 09:32:07,761 INFO Connecting to TGC socket...
2019-10-30 09:32:08,788 INFO Connected.
2019-10-30 09:32:08,789 INFO Recording brain data...
2019-10-30 09:47:10,228 INFO Connecting to TGC socket...
2019-10-30 09:47:11,244 INFO Connected.
2019-10-30 09:47:11,245 INFO Recording brain data...
2019-10-30 10:31:16,115 INFO Connecting to TGC socket...
2019-10-30 10:31:17,135 INFO Connected.
2019-10-30 10:31:17,136 INFO Recording brain data...
2019-10-30 10:31:17,725 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 125, in <module>
    conn.record_data()
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 84, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-30 10:31:17,725 ERROR No connection with TGC socket
2019-10-30 10:32:32,411 INFO Connecting to TGC socket...
2019-10-30 10:32:33,430 INFO Connected.
2019-10-30 10:32:33,431 INFO Recording brain data...
2019-10-30 10:35:42,518 INFO Connecting to TGC socket...
2019-10-30 10:35:43,535 INFO Connected.
2019-10-30 10:35:43,536 INFO Recording brain data...
2019-10-30 10:53:59,145 INFO Connecting to TGC socket...
2019-10-30 10:54:00,185 INFO Connected.
2019-10-30 10:54:00,186 INFO Recording brain data...
2019-10-30 10:57:05,741 INFO Connecting to TGC socket...
2019-10-30 10:57:06,761 INFO Connected.
2019-10-30 10:57:06,762 INFO Recording brain data...
2019-10-30 10:57:34,721 INFO Connecting to TGC socket...
2019-10-30 10:57:35,757 INFO Connected.
2019-10-30 10:57:35,758 INFO Recording brain data...
2019-10-30 10:57:36,370 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 131, in <module>
    conn.record_data()
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 85, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-30 10:57:36,370 ERROR No connection with TGC socket
2019-10-30 10:58:00,515 INFO Connecting to TGC socket...
2019-10-30 10:58:01,543 INFO Connected.
2019-10-30 10:58:01,544 INFO Recording brain data...
2019-10-30 11:02:47,148 INFO Connecting to TGC socket...
2019-10-30 11:02:48,170 INFO Connected.
2019-10-30 11:02:48,171 INFO Recording brain data...
2019-10-30 11:03:47,007 INFO Connecting to TGC socket...
2019-10-30 11:03:48,036 INFO Connected.
2019-10-30 11:03:48,037 INFO Recording brain data...
2019-10-30 11:04:41,394 INFO Connecting to TGC socket...
2019-10-30 11:04:42,428 INFO Connected.
2019-10-30 11:04:42,428 INFO Recording brain data...
2019-10-30 11:05:02,311 INFO Connecting to TGC socket...
2019-10-30 11:05:03,376 INFO Connected.
2019-10-30 11:05:03,376 INFO Recording brain data...
2019-10-30 11:05:23,108 INFO Connecting to TGC socket...
2019-10-30 11:05:24,131 INFO Connected.
2019-10-30 11:05:24,131 INFO Recording brain data...
2019-10-30 11:07:06,376 INFO Connecting to TGC socket...
2019-10-30 11:07:07,402 INFO Connected.
2019-10-30 11:07:07,402 INFO Recording brain data...
2019-10-30 12:45:07,351 INFO Connecting to TGC socket...
2019-10-30 12:45:08,362 INFO Connected.
2019-10-30 12:45:08,362 INFO Recording brain data...
2019-10-30 12:45:28,932 INFO Connecting to TGC socket...
2019-10-30 12:45:29,941 INFO Connected.
2019-10-30 12:45:29,941 INFO Recording brain data...
2019-10-30 13:24:47,473 INFO Connecting to TGC socket...
2019-10-30 13:24:48,494 INFO Connected.
2019-10-30 13:24:48,494 INFO Recording brain data...
2019-10-30 13:28:01,402 INFO Connecting to TGC socket...
2019-10-30 13:28:02,422 INFO Connected.
2019-10-30 13:28:02,422 INFO Recording brain data...
2019-10-30 13:31:56,940 INFO Connecting to TGC socket...
2019-10-30 13:31:57,952 INFO Connected.
2019-10-30 13:31:57,953 INFO Recording brain data...
2019-10-30 13:35:28,979 INFO Connecting to TGC socket...
2019-10-30 13:35:30,012 INFO Connected.
2019-10-30 13:35:30,012 INFO Recording brain data...
2019-10-30 13:35:55,919 INFO Connecting to TGC socket...
2019-10-30 13:35:56,931 INFO Connected.
2019-10-30 13:35:56,931 INFO Recording brain data...
2019-10-30 13:36:25,666 INFO Connecting to TGC socket...
2019-10-30 13:36:26,677 INFO Connected.
2019-10-30 13:36:26,678 INFO Recording brain data...
2019-10-30 13:38:13,780 INFO Connecting to TGC socket...
2019-10-30 13:38:14,798 INFO Connected.
2019-10-30 13:38:14,798 INFO Recording brain data...
2019-10-30 13:39:14,942 INFO Connecting to TGC socket...
2019-10-30 13:39:15,982 INFO Connected.
2019-10-30 13:39:15,983 INFO Recording brain data...
2019-10-30 13:55:05,266 INFO Connecting to TGC socket...
2019-10-30 13:55:06,286 INFO Connected.
2019-10-30 13:55:06,287 INFO Recording brain data...
2019-10-30 13:55:06,836 ERROR Exception:
Traceback (most recent call last):
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 132, in <module>
    conn.record_data()
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 85, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-30 13:55:06,837 ERROR No connection with TGC socket
2019-10-30 13:55:40,689 INFO Connecting to TGC socket...
2019-10-30 13:55:41,703 INFO Connected.
2019-10-30 13:55:41,703 INFO Recording brain data...
2019-10-30 13:55:42,385 ERROR Exception:
Traceback (most recent call last):
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 132, in <module>
    conn.record_data()
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 85, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-30 13:55:42,386 ERROR No connection with TGC socket
2019-10-30 13:56:07,333 INFO Connecting to TGC socket...
2019-10-30 13:56:08,359 INFO Connected.
2019-10-30 13:56:08,360 INFO Recording brain data...
2019-10-30 13:56:08,920 ERROR Exception:
Traceback (most recent call last):
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 132, in <module>
    conn.record_data()
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 85, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-30 13:56:08,921 ERROR No connection with TGC socket
2019-10-30 13:57:21,217 INFO Connecting to TGC socket...
2019-10-30 13:57:22,231 INFO Connected.
2019-10-30 13:57:22,232 INFO Recording brain data...
2019-10-30 13:57:57,880 INFO Connecting to TGC socket...
2019-10-30 13:57:58,891 INFO Connected.
2019-10-30 13:57:58,891 INFO Recording brain data...
2019-10-30 13:59:39,368 INFO Connecting to TGC socket...
2019-10-30 13:59:40,400 INFO Connected.
2019-10-30 13:59:40,400 INFO Recording brain data...
2019-10-30 14:01:17,335 INFO Connecting to TGC socket...
2019-10-30 14:01:18,347 INFO Connected.
2019-10-30 14:01:18,348 INFO Recording brain data...
2019-10-30 14:07:41,464 INFO Connecting to TGC socket...
2019-10-30 14:07:42,499 INFO Connected.
2019-10-30 14:07:42,499 INFO Recording brain data...
2019-10-30 14:08:59,585 INFO Connecting to TGC socket...
2019-10-30 14:09:00,603 INFO Connected.
2019-10-30 14:09:00,604 INFO Recording brain data...
2019-10-30 14:09:47,982 INFO Connecting to TGC socket...
2019-10-30 14:09:49,011 INFO Connected.
2019-10-30 14:09:49,012 INFO Recording brain data...
2019-10-30 14:10:26,936 INFO Connecting to TGC socket...
2019-10-30 14:10:27,948 INFO Connected.
2019-10-30 14:10:27,948 INFO Recording brain data...
2019-10-30 14:11:23,911 INFO Connecting to TGC socket...
2019-10-30 14:11:24,936 INFO Connected.
2019-10-30 14:11:24,937 INFO Recording brain data...
2019-10-30 14:12:35,044 INFO Connecting to TGC socket...
2019-10-30 14:12:36,055 INFO Connected.
2019-10-30 14:12:36,056 INFO Recording brain data...
2019-10-30 15:08:32,241 INFO Connecting to TGC socket...
2019-10-30 15:08:33,264 INFO Connected.
2019-10-30 15:08:33,265 INFO Recording brain data...
2019-10-30 15:09:18,797 INFO Connecting to TGC socket...
2019-10-30 15:09:19,808 INFO Connected.
2019-10-30 15:09:19,809 INFO Recording brain data...
2019-10-30 15:11:08,912 INFO Connecting to TGC socket...
2019-10-30 15:11:09,936 INFO Connected.
2019-10-30 15:11:09,937 INFO Recording brain data...
2019-10-30 15:23:37,727 INFO Connecting to TGC socket...
2019-10-30 15:23:38,745 INFO Connected.
2019-10-30 15:23:38,745 INFO Recording brain data...
2019-10-30 15:24:31,068 INFO Connecting to TGC socket...
2019-10-30 15:24:32,092 INFO Connected.
2019-10-30 15:24:32,092 INFO Recording brain data...
2019-10-30 15:26:23,850 INFO Connecting to TGC socket...
2019-10-30 15:26:24,862 INFO Connected.
2019-10-30 15:26:24,863 INFO Recording brain data...
2019-10-30 15:27:23,705 INFO Connecting to TGC socket...
2019-10-30 15:27:24,728 INFO Connected.
2019-10-30 15:27:24,729 INFO Recording brain data...
2019-10-30 15:28:08,055 INFO Connecting to TGC socket...
2019-10-30 15:28:09,072 INFO Connected.
2019-10-30 15:28:09,073 INFO Recording brain data...
2019-10-30 15:28:37,451 INFO Connecting to TGC socket...
2019-10-30 15:28:38,463 INFO Connected.
2019-10-30 15:28:38,463 INFO Recording brain data...
2019-10-30 15:29:32,543 INFO Connecting to TGC socket...
2019-10-30 15:29:33,555 INFO Connected.
2019-10-30 15:29:33,555 INFO Recording brain data...
2019-10-30 15:34:52,554 INFO Connecting to TGC socket...
2019-10-30 15:34:53,578 INFO Connected.
2019-10-30 15:34:53,579 INFO Recording brain data...
2019-10-30 15:35:47,054 ERROR Exception:
Traceback (most recent call last):
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 132, in <module>
    conn.record_data()
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 84, in record_data
    self.data = self.sock.read_until(b'\r')
  File "C:\Users\Chirag Bellara\AppData\Local\Programs\Python\Python36\lib\telnetlib.py", line 327, in read_until
    return self.read_very_lazy()
  File "C:\Users\Chirag Bellara\AppData\Local\Programs\Python\Python36\lib\telnetlib.py", line 403, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed
2019-10-30 15:35:47,058 ERROR No connection with TGC socket
2019-10-30 15:36:24,313 INFO Connecting to TGC socket...
2019-10-30 15:36:25,566 INFO Connecting to TGC socket...
2019-10-30 15:36:26,582 INFO Connected.
2019-10-30 15:36:26,583 INFO Recording brain data...
2019-10-30 15:37:12,712 INFO Connecting to TGC socket...
2019-10-30 15:37:13,732 INFO Connected.
2019-10-30 15:37:13,732 INFO Recording brain data...
2019-10-30 15:41:07,664 INFO Connecting to TGC socket...
2019-10-30 15:41:08,693 INFO Connected.
2019-10-30 15:41:08,693 INFO Recording brain data...
2019-10-30 15:42:20,093 ERROR Exception:
Traceback (most recent call last):
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 132, in <module>
    conn.record_data()
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 84, in record_data
    self.data = self.sock.read_until(b'\r')
  File "C:\Users\Chirag Bellara\AppData\Local\Programs\Python\Python36\lib\telnetlib.py", line 327, in read_until
    return self.read_very_lazy()
  File "C:\Users\Chirag Bellara\AppData\Local\Programs\Python\Python36\lib\telnetlib.py", line 403, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed
2019-10-30 15:42:20,095 ERROR No connection with TGC socket
2019-10-30 15:42:56,828 INFO Connecting to TGC socket...
2019-10-30 15:42:57,840 INFO Connected.
2019-10-30 15:42:57,840 INFO Recording brain data...
2019-10-30 15:44:12,757 INFO Connecting to TGC socket...
2019-10-30 15:44:13,772 INFO Connected.
2019-10-30 15:44:13,772 INFO Recording brain data...
2019-10-30 15:55:53,067 INFO Connecting to TGC socket...
2019-10-30 15:55:54,085 INFO Connected.
2019-10-30 15:55:54,085 INFO Recording brain data...
2019-10-30 15:57:27,731 INFO Connecting to TGC socket...
2019-10-30 15:57:28,752 INFO Connected.
2019-10-30 15:57:28,752 INFO Recording brain data...
2019-10-30 15:59:49,516 INFO Connecting to TGC socket...
2019-10-30 15:59:50,533 INFO Connected.
2019-10-30 15:59:50,533 INFO Recording brain data...
2019-10-30 16:01:52,450 INFO Connecting to TGC socket...
2019-10-30 16:01:53,471 INFO Connected.
2019-10-30 16:01:53,471 INFO Recording brain data...
2019-10-30 16:03:04,270 INFO Connecting to TGC socket...
2019-10-30 16:03:05,297 INFO Connected.
2019-10-30 16:03:05,297 INFO Recording brain data...
2019-10-30 16:08:20,573 INFO Connecting to TGC socket...
2019-10-30 16:08:21,594 INFO Connected.
2019-10-30 16:08:21,595 INFO Recording brain data...
2019-10-30 16:10:47,773 INFO Connecting to TGC socket...
2019-10-30 16:10:48,794 INFO Connected.
2019-10-30 16:10:48,794 INFO Recording brain data...
2019-10-30 16:11:35,376 INFO Connecting to TGC socket...
2019-10-30 16:11:36,392 INFO Connected.
2019-10-30 16:11:36,392 INFO Recording brain data...
2019-10-30 16:11:56,098 INFO Connecting to TGC socket...
2019-10-30 16:11:57,110 INFO Connected.
2019-10-30 16:11:57,111 INFO Recording brain data...
2019-10-30 16:12:56,762 INFO Connecting to TGC socket...
2019-10-30 16:12:57,776 INFO Connected.
2019-10-30 16:12:57,776 INFO Recording brain data...
2019-10-30 16:27:15,811 INFO Connecting to TGC socket...
2019-10-30 16:27:16,828 INFO Connected.
2019-10-30 16:27:16,829 INFO Recording brain data...
2019-10-30 16:28:23,189 INFO Connecting to TGC socket...
2019-10-30 16:28:24,202 INFO Connected.
2019-10-30 16:28:24,202 INFO Recording brain data...
2019-10-30 16:29:42,165 INFO Connecting to TGC socket...
2019-10-30 16:29:43,178 INFO Connected.
2019-10-30 16:29:43,179 INFO Recording brain data...
2019-10-30 16:30:33,172 INFO Connecting to TGC socket...
2019-10-30 16:30:34,193 INFO Connected.
2019-10-30 16:30:34,193 INFO Recording brain data...
2019-10-30 16:30:34,778 ERROR Exception:
Traceback (most recent call last):
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 132, in <module>
    conn.record_data()
  File "D:\BE Project\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 85, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-30 16:30:34,779 ERROR No connection with TGC socket
2019-10-30 16:35:21,658 INFO Connecting to TGC socket...
2019-10-30 16:35:22,671 INFO Connected.
2019-10-30 16:35:22,671 INFO Recording brain data...
2019-10-30 16:36:09,906 INFO Connecting to TGC socket...
2019-10-30 16:36:10,938 INFO Connected.
2019-10-30 16:36:10,939 INFO Recording brain data...
2019-10-30 16:37:15,761 INFO Connecting to TGC socket...
2019-10-30 16:37:16,777 INFO Connected.
2019-10-30 16:37:16,778 INFO Recording brain data...
2019-10-30 16:38:56,011 INFO Connecting to TGC socket...
2019-10-30 16:38:57,025 INFO Connected.
2019-10-30 16:38:57,025 INFO Recording brain data...
2019-10-30 16:39:50,862 INFO Connecting to TGC socket...
2019-10-30 16:39:51,881 INFO Connected.
2019-10-30 16:39:51,881 INFO Recording brain data...
2019-10-30 16:40:47,784 INFO Connecting to TGC socket...
2019-10-30 16:40:48,795 INFO Connected.
2019-10-30 16:40:48,795 INFO Recording brain data...
2019-10-30 16:41:50,226 INFO Connecting to TGC socket...
2019-10-30 16:41:51,243 INFO Connected.
2019-10-30 16:41:51,243 INFO Recording brain data...
2019-10-30 16:47:53,556 INFO Connecting to TGC socket...
2019-10-30 16:47:54,591 INFO Connected.
2019-10-30 16:47:54,591 INFO Recording brain data...
2019-10-30 16:49:22,085 INFO Connecting to TGC socket...
2019-10-30 16:49:23,109 INFO Connected.
2019-10-30 16:49:23,109 INFO Recording brain data...
2019-10-30 16:51:33,388 INFO Connecting to TGC socket...
2019-10-30 16:51:34,422 INFO Connected.
2019-10-30 16:51:34,423 INFO Recording brain data...
